repos:

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.261'
    hooks:
    -   id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
        exclude: ^.*\b(assets)\b.*$

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
        exclude: '\.(xml|json)$|^.*\b(assets)\b.*'
