repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
    -   id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
        exclude: ^.*\b(assets)\b.*$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
        exclude: '\.(xml|json)$|^.*\b(assets)\b.*'
